# Generated by Django 5.2.5 on 2025-08-27 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mogi',
            name='played_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
